CREATE TABLE IF NOT EXISTS users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- No unique constraint on uid. We go with the assumption that
    -- uuid is always unique
    uid uuid NOT NULL,
    name varchar(127) NOT NULL,
    email varchar(127) NOT NULL,
    password_hash varchar(255) NOT NULL,
    created_at timestamp DEFAULT current_timestamp NOT NULL,
    UNIQUE(email)
);

